let state=null,currentEditor=null;const $=id=>document.getElementById(id);
async function api(url,opts={}){const r=await fetch(url,{...opts,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Ошибка');return d}
async function load(){try{state=await api('/api/admin');$('login').classList.add('hidden');$('panel').classList.remove('hidden');render()}catch(e){$('err').textContent='Нет доступа. Открой админку по секретной ссылке.'}}
function render(){renderOverview();renderCards();renderStats();renderAccess()}
function renderOverview(){const g=state.global||{};$('overview').innerHTML=`<div class="metric"><span>ИГРОКОВ</span><b>${g.players||0}</b></div><div class="metric"><span>ПРОХОЖДЕНИЙ</span><b>${g.attempts||0}</b></div><div class="metric"><span>ПРАВИЛЬНЫХ</span><b>${g.correct||0}</b></div><div class="metric accent"><span>СТРИМЕРОВ</span><b>${state.streamers.filter(s=>s.active!==false).length}/${state.streamers.length}</b></div>`}
function renderCards(){$('editors').innerHTML=state.streamers.map((s,i)=>`<button class="streamerTile ${s.active===false?'off':''}" onclick="openEditor(${i})"><div class="tileNo">0${i+1}</div><div class="tileAvatar"><img src="${esc(s.image)}" onerror="this.src='https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(s.name)}'"></div><strong>${esc(s.name)}</strong><span>${s.active===false?'СКРЫТ':'АКТИВЕН'} · ${s.questions.length} ВОПР.</span><em class="mediaBadge">${s.resultMedia?.photos?.length||0} фото ${s.resultMedia?.audio?.url?'· трек':''}</em></button>`).join('')}
function renderStats(){const g=state.global||{},players=state.users||[];$('stats').innerHTML=`<div class="statsSummary"><div><b>${g.players||0}</b><span>игроков</span></div><div><b>${g.attempts||0}</b><span>тестов</span></div><div><b>${g.correct||0}</b><span>правильных</span></div></div>${players.length?`<div class="playerTable">${players.map(p=>`<div class="playerRow"><b>ID ${p.id}</b><span>${p.name||'Игрок'}</span><span>${p.attempts||0} проходов</span><strong>${p.correct||0} правильных</strong><div class="userActions"><button onclick="resetStats(${p.id})">Сбросить</button><button onclick="banUser(${p.id})">Забанить</button><button onclick="changeId(${p.id})">Сменить ID</button></div></div>`).join('')}</div>`:'<div class="empty">Пока никто не прошёл тест.</div>'}`}
function renderAccess(){const admins=state.admins||[];$('access').innerHTML=`<div class="accessForm"><div class="accessInputWrap"><span>#</span><input id="accessId" type="number" min="0" max="100000" placeholder="ID пользователя"><button onclick="grantAdmin()">Выдать доступ</button></div><div class="accessSub">Укажи ID игрока — права администратора появятся сразу.</div></div><div class="adminList">${admins.length?admins.map(a=>`<div class="playerRow"><b>ID ${a.id}</b><span>${a.name||'Игрок'}</span><strong>АДМИН</strong>${a.id!=null?`<button class="revoke" onclick="revokeAdmin(${a.id})">Забрать</button>`:''}</div>`).join(''):'<div class="empty">Дополнительных администраторов пока нет.</div>'}</div><small class="secretHint">Секретная ссылка владельца: ${esc(location.origin+state.masterRoute)}</small>`}
async function grantAdmin(){const id=Number($('accessId').value);if(!Number.isInteger(id))return alert('Введи ID');try{await api('/api/admin/grant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});$('accessId').value='';state=await api('/api/admin');render()}catch(e){alert(e.message)}}
async function revokeAdmin(id){if(!confirm('Забрать права администратора у ID '+id+'?'))return;try{await api('/api/admin/revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});state=await api('/api/admin');render()}catch(e){alert(e.message)}}
function openEditor(i){currentEditor=i;const s=state.streamers[i],m=s.resultMedia||{audio:{},photos:[]},a=m.audio||{};$('modalContent').innerHTML=`<div class="modalEyebrow">STREAMER 0${i+1}</div><h2>${esc(s.name)}</h2><div class="formGrid"><label>Ник<input id="m-name" value="${esc(s.name)}"></label><label>URL аватарки<input id="m-image" value="${esc(s.image)}"></label></div><div class="visibilityRow"><div><b>Показывать на сайте</b><small>Если выключить, история прохождений сохранится.</small></div><label class="switch"><input id="m-active" type="checkbox" ${s.active!==false?'checked':''}><span></span></label></div><div class="mediaEditor"><div class="mediaTitle"><div><span>ФИНАЛЬНЫЙ ТРЕК</span><h3>Музыка после завершения</h3></div><label class="switch"><input id="m-audio-enabled" type="checkbox" ${a.enabled?'checked':''}><span></span></label></div><div class="mediaGrid"><label>Прямая ссылка на аудиофайл<input id="m-audio-url" value="${esc(a.url||'')}" placeholder="https://site.com/track.mp3"></label><div class="timeGrid"><label>Начать с, сек.<input id="m-audio-start" type="number" min="0" step="0.1" value="${Number(a.start)||0}"></label><label>Остановить на, сек.<input id="m-audio-end" type="number" min="0" step="0.1" value="${Number(a.end)||0}"></label></div></div><p class="mediaHint">Используй прямую ссылку на MP3 / OGG / WAV / M4A. Если «до» = 0, трек играет до конца.</p></div><div class="mediaEditor"><div class="mediaTitle"><div><span>ФОТОГАЛЕРЕЯ ФИНАЛА</span><h3>10–20 фотографий</h3></div><b class="photoCount" id="photoCount">${m.photos?.length||0}/20</b></div><div id="photoInputs" class="photoInputs">${(m.photos||[]).map((url,pi)=>photoRow(url,pi)).join('')}</div><button class="addPhoto" onclick="addPhotoInput()">+ Добавить фото</button><p class="mediaHint">Нужно минимум 10 фотографий, максимум 20. Можно вставлять прямые ссылки на изображения.</p></div><div class="questions" id="m-questions">${s.questions.map((q,qi)=>questionHtml(q,qi)).join('')}</div><div class="modalActions"><button class="secondary" onclick="addQuestion()">+ Вопрос</button><button class="save" onclick="saveEditor()">Сохранить изменения</button></div>`;$('modal').classList.remove('hidden');updatePhotoCount()}
function photoRow(url,pi){return `<div class="photoRow"><span>${String(pi+1).padStart(2,'0')}</span><input data-photo value="${esc(url)}" placeholder="https://site.com/photo-${pi+1}.jpg"><button onclick="removePhotoInput(this)">×</button></div>`}
function addPhotoInput(){const box=$('photoInputs');if(!box||box.children.length>=20)return;box.insertAdjacentHTML('beforeend',photoRow('',box.children.length));updatePhotoCount()}
function removePhotoInput(btn){btn.closest('.photoRow')?.remove();[...document.querySelectorAll('.photoRow')].forEach((el,i)=>el.querySelector('span').textContent=String(i+1).padStart(2,'0'));updatePhotoCount()}
function updatePhotoCount(){const n=document.querySelectorAll('.photoRow').length;const el=$('photoCount');if(el){el.textContent=n+'/20';el.classList.toggle('ok',n>=10&&n<=20)}}
function questionHtml(q,qi){return `<div class="qCard"><div class="qHead"><b>ВОПРОС ${qi+1}</b><button onclick="deleteQuestion(${qi})">Удалить</button></div><input class="qText" data-q value="${esc(q.q)}"><div class="answerGrid">${q.answers.map((a,ai)=>`<input data-a="${ai}" value="${esc(a)}" placeholder="Ответ ${ai+1}">`).join('')}</div><select data-c>${q.answers.map((_,ai)=>`<option value="${ai}" ${ai===q.correct?'selected':''}>Правильный ответ: ${ai+1}</option>`).join('')}</select></div>`}
function addQuestion(){state.streamers[currentEditor].questions.push({q:'Новый вопрос',answers:['Вариант 1','Вариант 2','Вариант 3','Вариант 4'],correct:0});openEditor(currentEditor)}
function deleteQuestion(qi){if(state.streamers[currentEditor].questions.length<=1)return;state.streamers[currentEditor].questions.splice(qi,1);openEditor(currentEditor)}
async function saveEditor(){const i=currentEditor,s=state.streamers[i],qs=[...document.querySelectorAll('#m-questions .qCard')].map(el=>({q:el.querySelector('[data-q]').value,answers:[...el.querySelectorAll('[data-a]')].map(x=>x.value),correct:Number(el.querySelector('[data-c]').value)}));const photos=[...document.querySelectorAll('[data-photo]')].map(x=>x.value.trim()).filter(Boolean);if(photos.length>0&&photos.length<10)return alert('Для галереи нужно минимум 10 фотографий.');if(photos.length>20)return alert('Максимум 20 фотографий.');const audioUrl=$('m-audio-url').value.trim(),start=Math.max(0,Number($('m-audio-start').value)||0),end=Math.max(0,Number($('m-audio-end').value)||0);if(end>0&&end<=start)return alert('Время окончания должно быть больше времени начала.');try{await api(`/api/admin/streamers/${i}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('m-name').value,image:$('m-image').value,active:$('m-active').checked,questions:qs,resultMedia:{audio:{url:audioUrl,start,end,enabled:$('m-audio-enabled').checked&&!!audioUrl},photos}})});state=await api('/api/admin');closeEditor();render()}catch(e){alert(e.message)}}
function closeEditor(){currentEditor=null;$('modal').classList.add('hidden')}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
load();setInterval(async()=>{if(currentEditor!==null)return;try{state=await api('/api/admin');render()}catch{}},5000);
async function resetStats(id){if(!confirm('Сбросить всю статистику ID '+id+'?'))return;try{await api('/api/admin/reset/'+id,{method:'POST'});state=await api('/api/admin');render()}catch(e){alert(e.message)}}
async function banUser(id){if(!confirm('Забанить ID '+id+'?'))return;try{await api('/api/admin/ban/'+id,{method:'POST'});state=await api('/api/admin');render()}catch(e){alert(e.message)}}
async function changeId(oldId){const v=prompt('Новый ID для пользователя '+oldId+' (0–100000):');if(v===null)return;const newId=Number(v);if(!Number.isInteger(newId))return alert('Неверный ID');try{await api('/api/admin/change-id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({oldId,newId})});state=await api('/api/admin');render()}catch(e){alert(e.message)}}
