let adminId="", state=null;
const $=id=>document.getElementById(id);
async function login(){adminId=$("adminId").value.trim();const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:adminId})});if(!r.ok){$("err").textContent="Неверный ID";return}load();}
async function load(){const r=await fetch("/api/admin",{headers:{"x-admin-id":adminId}});state=await r.json();$("login").classList.add("hidden");$("panel").classList.remove("hidden");render();}
function render(){ $("editors").innerHTML=state.streamers.map((s,si)=>`<div class="editor"><h2>${si+1}. ${esc(s.name)}</h2><label>Название</label><input class="input" id="name-${si}" value="${esc(s.name)}"><label>URL картинки</label><input class="input" id="img-${si}" value="${esc(s.image)}"><div id="qs-${si}">${s.questions.map((q,qi)=>questionHtml(si,qi,q)).join("")}</div><button class="btn" onclick="addQ(${si})">+ Добавить вопрос</button> <button class="btn save" onclick="save(${si})">Сохранить стримера</button></div>`).join("");$("stats").innerHTML=state.users.length?state.users.map(u=>`<div class="stat"><b>${esc(u.id)}</b> — прохождений: ${u.attempts}, правильных: ${u.correct}</div>`).join(""):"Пока нет прохождений";}
function questionHtml(si,qi,q){return `<div class="q"><b>Вопрос ${qi+1}</b><input class="input qtext-${si}" value="${esc(q.q)}" placeholder="Текст вопроса"><div class="answers">${q.answers.map((a,ai)=>`<input class="input ans-${si}-${qi}" data-ai="${ai}" value="${esc(a)}" placeholder="Ответ ${ai+1}">`).join("")}</div><label>Правильный ответ</label><select class="input correct-${si}">${q.answers.map((_,ai)=>`<option value="${ai}" ${ai===q.correct?"selected":""}>${ai+1}</option>`).join("")}</select><button class="btn danger" onclick="removeQ(${si},${qi})">Удалить вопрос</button></div>`;}
function addQ(si){state.streamers[si].questions.push({q:"Новый вопрос",answers:["Вариант 1","Вариант 2","Вариант 3","Вариант 4"],correct:0});render();}
function removeQ(si,qi){state.streamers[si].questions.splice(qi,1);render();}
async function save(si){const s=state.streamers[si], qs=[...document.querySelectorAll(`#qs-${si} .q`)].map((el,qi)=>({q:el.querySelector(`.qtext-${si}`).value,answers:[...el.querySelectorAll(`.ans-${si}-${qi}`)].map(x=>x.value),correct:Number(el.querySelector(`.correct-${si}`).value)}));const body={name:$(`name-${si}`).value,image:$(`img-${si}`).value,questions:qs};const r=await fetch(`/api/admin/streamers/${si}`,{method:"PUT",headers:{"Content-Type":"application/json","x-admin-id":adminId},body:JSON.stringify(body)});if(r.ok){state=await (await fetch("/api/admin",{headers:{"x-admin-id":adminId}})).json();render();alert("Сохранено");}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
